//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLADMIN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLADMIN()
        {
            this.TBLBLOGS = new HashSet<TBLBLOGS>();
        }
    
        public int ID { get; set; }
        public string NAME_AND_SURNAME { get; set; }
        public string USERNAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string TWITTER { get; set; }
        public string INSTAGRAM { get; set; }
        public string LINKEDIN { get; set; }
        public string PASSWORD { get; set; }
        public string IMAGE { get; set; }
        public Nullable<int> ADMINROLEID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBLOGS> TBLBLOGS { get; set; }
        public virtual TBLADMINROLE TBLADMINROLE { get; set; }
    }
}
