//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLABOUT
    {
        public int ID { get; set; }
        public string TITLE { get; set; }
        public string ALTTITLE { get; set; }
        public string LİST1 { get; set; }
        public string LİST2 { get; set; }
        public string LİST3 { get; set; }
        public string IMAGE { get; set; }
        public string IMAGE2 { get; set; }
        public string IMAGE3 { get; set; }
    }
}
