//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBLOGS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLBLOGS()
        {
            this.TBLCOMMENT = new HashSet<TBLCOMMENT>();
        }
    
        public int ID { get; set; }
        public string TITLE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<int> CATEGORYID { get; set; }
        public Nullable<int> ADMINID { get; set; }
        public string IMAGE { get; set; }
    
        public virtual TBLADMIN TBLADMIN { get; set; }
        public virtual TBLCATEGORY TBLCATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCOMMENT> TBLCOMMENT { get; set; }
    }
}
