//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBLOGS
    {
        public int ID { get; set; }
        public string TITLE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<int> CATEGORYID { get; set; }
        public Nullable<int> ADMINID { get; set; }
        public Nullable<int> COMMENTID { get; set; }
        public string IMAGE { get; set; }
    
        public virtual TBLADMIN TBLADMIN { get; set; }
        public virtual TBLCATEGORY TBLCATEGORY { get; set; }
        public virtual TBLCOMMENT TBLCOMMENT { get; set; }
    }
}
