//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCOMMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLCOMMENT()
        {
            this.TBLBLOGS = new HashSet<TBLBLOGS>();
        }
    
        public int ID { get; set; }
        public string NAME_AND_SURNAME { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string COMMENT { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBLOGS> TBLBLOGS { get; set; }
    }
}
